# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (Supabase)
# ==========================================
database:
  # La URL limpia (sin el user y password al final)
  url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres

  # El usuario exacto que te marca Supabase
  username: postgres.feqgxfxokblhslfrovlv

  # Tu contraseña real entre comillas
  password: "TU_CONTRASEÑA_REAL_AQUI"


  # ==========================================
  # SISTEMA DE PESCA (CRIATURAS MARINAS)
  # ==========================================
  pesca:
    probabilidad_base_scc: 5.0 # Todo jugador tiene 5% base de pescar un mob
    criaturas:
      emperador:
        nivel_requerido: 25
        mob: ELDER_GUARDIAN
        nombre: "&4&lEmperador de las Profundidades"
        vida: 500.0
        arma_mano: "NONE"
      fango:
        nivel_requerido: 15
        mob: DROWNED
        nombre: "&5&lMonstruo del Fango"
        vida: 250.0
        arma_mano: "TRIDENT"
      caminante:
        nivel_requerido: 5
        mob: WITHER_SKELETON
        nombre: "&9Caminante Acuático"
        vida: 100.0
        arma_mano: "STONE_SWORD"
      marinero:
        nivel_requerido: 1
        mob: ZOMBIE
        nombre: "&aMarinero Perdido"
        vida: 50.0
        arma_mano: "NONE"