name: MiPrimerPlugin
version: 1.0
main: me.tunombre.server.Main
api-version: '1.21'
softdepend: [PlaceholderAPI, MythicMobs]
depend: [eco, AuraSkills, Nexo]
commands:
  test:
    description: Mi comando de prueba
  nexo:
    description: Comando de administracion del Nexo
    permission: nexo.admin
  desguace:
    description: Abre el menu de reciclaje
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.postgresql:postgresql:42.7.2
